### ISSUE TITLE
2 levels Context Maps

### ISSUE THREAD

**Issue by Max-Git** [ddd-crew/context-mapping#5]
Hello @mploed 

I was wondering if you had already seen or done such a thing: having a 2 levels context maps where 1st level would focus only on team relationships and 2nd level, only on context map patterns.

Here's an example:
(and yes, obviously the Cus-->Sup relationship should be the other way round ;) )

**Team relationships**
![Team](https://user-images.githubusercontent.com/4160238/102604214-23316580-4124-11eb-9f9a-b9692b63bcb5.jpg)

**Context map patterns**
![ContextMap](https://user-images.githubusercontent.com/4160238/102604257-33494500-4124-11eb-96ad-dbb933ab9d89.jpg)

**Both**
![Both](https://user-images.githubusercontent.com/4160238/102604307-4825d880-4124-11eb-9696-2a27af6972ea.jpg)

What do you think? Does it make sense or useful to separate both perspective? 

Thanks!

Maxime

**Comment by NTCoding** [comment]
I like this. I think it makes implicit concept that team relationships and model integrations are different aspects and it's important to consider both of them for each type of relationship.

**Comment by mploed** [comment]
Thanks @Max-Git

I always say that you are free to visualize various perspectives with context maps. For example:

- Team Relationships
- Governance 
- Model Flow / Propagation + APIs

The term "level" sounds a bit hierarchical to me and I don't see a clear hierarchy between those aspects. That's why I prefer using the term "perspective".

@NTCoding I would not propagate that you always have to use each perspective. In my opinion it depends which questions you want to answer in a visual way with context maps. When you design (sociotechnical) architectures then you have to consider both. But I have also used context maps to visualize political / governance issues to managers, then you only need a subset.

I agree with both of you that this is something that needs to be present in this repository. I'll take care of it!

**Comment by mploed** [comment]
Started a draft pull request for this!
